
services:
  ddns-tracker:
    build: .
    container_name: ddns-tracker
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ddns-network

networks:
  ddns-network:
    driver: bridge
